language: python
python:
  - "3.4"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls"
  - "pip install ."
  
before_script:
  - "git clone https://github.com/owlcollab/owltools.git"
  - "cd owltools/OWLTools-Parent/"
  - "mvn clean package -DskipTests=true"
  - "cd ../.."

# command to run tests
script: make test

after_success:
  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - kshefchek@gmail.com
    - nlwashington@lbl.gov
    - larawayb@ohsu.edu
